# <span style="color:darkblue"> Lecture 8: Local/Global and Apply </span>

<font size = "5">

In the previous lecture we ...

- Worked through the definition of functions
- Illustrated some examples

In this lecture, we will ...

- Discuss the syntax of functions (local/global)
- Apply functions to multiple elements in a data frame
- Introduce ".py" files

## <span style="color:darkblue"> I. Import Libraries </span>

In [1]:
# the "pandas" library is for manipualting datasets

import pandas as pd
import numpy as np

In [4]:

message_hello = "hello"
print(message_hello + " world")
print(3 * 2)

#py = alternative way of storing stuff, other than jupyter scripts. 
#py = common way that python files are stored and shared.

hello world
6

<font size = "5">

Any "global" variable can be referenced inside functions

- However, this can lead to mistakes
- Preferrably, include **all** the inputs as parameters

<font size = "5">

$f(x,y,z) = x + y + z$

In [7]:
# Correct Example:
def fn_add_recommended(x,y,z):
    return(x + y + z)

print(fn_add_recommended(x = 1, y = 2, z = 5))
print(fn_add_recommended(x = 1, y = 2, z = 10)) # z is the parameter, 10 is the argument

print(fn_add_recommended("my name is", "athena", "tian")) # donn't need to write the parameter, just defines itself

8
13
my name isathenatian

In [6]:
# Example that runs (but not recommended)
# Python will try to fill in any missing inputs
# with variables in the working environment
def fn_add_notrecommended(x,y):
    return(x + y + z)

z = 5
print(fn_add_notrecommended(x = 1, y = 2))
z = 10
print(fn_add_notrecommended(x = 1, y = 2))

z = "testing a string"
print(fn_add_notrecommended(x="does this work", y = "i hope so"))

8
13
does this worki hope sotesting a string

<font size ="5">

Variables defined inside functions are "local"

- Stored "temporarily" while running
- Includes: Parameters + Intermediate variables

<font size = "5">

Local variables supercede global variables

In [9]:
# This is an example where we define a quadratic function
# (x,y) are both local variables of the function
# 
# When we call the function, only the arguments matter.
# any intermediate value inside the function

# LIKE SCRATCH PAPER FOR CODING: don't need to be visible for the end user/reader (intermediate calculations, intermediate vars)
def fn_square(x):
    y = x**2
    return(y) # y is an intermediate var, not an immediate input

x = 10
y = -5 

# variables and functions can have the same name, so functions give a hierarchy of which one gets used. 
# python uses the hierarchy of functions 
# local vars always take precedence over global vars (within the function, but not in the global environment)

print(fn_square(x = 1))

print(x)
print(y)

1
10
-5

<font size = "5">

Local variables are **not** stored in the working environment

In [14]:
# The following code assigns a global variable x
# Inside the function

x = 5
y = 4

# changing one thing at a time in the function definition
print("Example 1:")
print(fn_square(x = 10))
print(x)
print(y)

print("Example 2:")
print(fn_square(x = 20)) # this only changes x locally
print(x)
print(y)

def fn_squarey(y):
    return y**1

print(fn_squarey(y)) # prints globally defined var
print(fn_squarey(y=15))

Example 1:
100
5
4
Example 2:
400
5
4
4
15

<font size = "5">

To permanently modify a variable, use the "global" command

In [16]:
def modify_x():
    global x
    x = x + 5

x = 1
# Now, running the function wil permanently increase x by 5.
modify_x()
print(x)

# If a variable is assigned a value anywhere within the function’s body, it’s assumed to be a local unless explicitly declared as global.
# Variables that are only referenced inside a function are implicitly global.
# We use a global keyword to use a global variable inside a function.
# There is no need to use global keywords outside a function.

6

In [19]:
modify_x()
print(x)

def change_x(): # having a function with global will permanently change x, until it's changed again
    global x
    x = x**2

x=3
print(change_x()) # returns none
print(x)

14
None
9

<font size = "5">

Try it yourself:

- What happens if we run "modify_x" twice?
- What happens if we add "global y" inside "fn_square"?

In [ ]:
# Write your own code here

25
625

## <span style="color:darkblue"> III. Operations over data frames (apply/map) </span>

<font size = "5">

Create an empty data frame

In [22]:
data  = pd.DataFrame() # empty data frame
# no columns, no rows
#pd.dataframe is a function

In [23]:
print(data) # start to populate the function/dataset

Empty DataFrame
Columns: []
Index: []

<font size = "5">

Add variables

In [ ]:
# The following are lists with values for different individuals
# "age" is the number of years
# "num_underage_siblings" is the total number of underage siblings
# "num_adult_siblings" is the total number of adult siblings

data["age"] = [18,29,15,32,6]
data["num_underage_siblings"] = [0,0,1,1,0]
data["num_adult_siblings"] = [1,0,0,1,0]
# creating a matrix

In [ ]:
data

   age  num_underage_siblings  num_adult_siblings
0   18                      0                   1
1   29                      0                   0
2   15                      1                   0
3   32                      1                   1
4    6                      0                   0

<font size = "5">

Define functions

In [29]:
# The first two functions return True/False depending on age constraints
# The third function returns the sum of two numbers
# The fourt function returns a string with the age bracket

fn_iseligible_vote = lambda age: age >= 18

fn_istwenties = lambda age: (age >= 20) & (age < 30) # evaluating 2 logical conditions


fn_sum = lambda x,y: x + y

def fn_agebracket(age):
    if (age >= 18):
        status = "Adult"
    elif (age >= 10) & (age < 18):
        status = "Adolescent"
    else:
        status = "Child"
    return(status)

print(fn_agebracket(16))
print(fn_agebracket(560))
print(fn_agebracket(-9))

Adolescent
Adult
Child

<font size = "5">
Applying functions with one argument: <br>

```python
 apply(myfunction)
 ```
 - Takes a dataframe series (a column vector) as an input
 - Computes function separately for each individual

In [32]:
# The fucntion "apply" will extract each element and return the function value
# It is similar to running a "for-loop" over each element

data["can_vote"]    = data["age"].apply(fn_iseligible_vote)
data["in_twenties"] = data["age"].apply(fn_istwenties)
data["age_bracket"] = data["age"].apply(fn_agebracket)


# NOTE: The following code also works:
# data["can_vote"]    = data["age"].apply(lambda age: age >= 18)
# data["in_twenties"] = data["age"].apply(lambda age: (age >= 20) & (age < 30))

display(data)

KeyError: 'age'

<font size = "5">

Creating a new variable

In [ ]:
data['new_var'] = data['age'].apply(lambda age: age >= 18)
data

# jupyter variables = dictionary and descriptive stats

KeyError: 'age'

<font size = "5">

Dropping an existing variable

In [30]:
data = data.drop(columns=['new_var'])
data

KeyError: "['new_var'] not found in axis"

<font size = "5">

Mapping functions with one or more arguments <br>

**Definition:** The ```map()``` function executes a <br>
specified function for each item in an iterable <br>
(such as a list or an array). <br>
 The item is sent to the function as a parameter.

```python
list(map(myfunction, list1,list2, ....))
```

In [35]:
list(map(fn_iseligible_vote, data["age"])) # map can do multiple arguments

KeyError: 'age'

In [36]:
# Repeat the above example with map
# We use list() to convert the output to a list
# The first argument of map() is a function
# The following arguments are the subarguments of the function

data["can_vote_map"] = list(map(fn_iseligible_vote, data["age"]))

KeyError: 'age'

In [ ]:
# In this example, there are more than two arguments

data["num_siblings"] = list(map(fn_sum,
                                data["num_underage_siblings"],
                                data["num_adult_siblings"]))

In [ ]:
list(map(fn_sum, data["num_underage_siblings"],
         data["num_adult_siblings"]))

[1, 0, 1, 2, 0]

In [ ]:
data["num_underage_siblings"] + data["num_adult_siblings"]

0    1
1    0
2    1
3    2
4    0
dtype: int64

In [ ]:
data["num_underage_siblings"]

0    0
1    0
2    1
3    1
4    0
Name: num_underage_siblings, dtype: int64

In [ ]:
data["num_adult_siblings"]

0    1
1    0
2    0
3    1
4    0
Name: num_adult_siblings, dtype: int64

<font size = "5">

<span style="color:darkgreen"> Recommended! </span>

- Arguments can be split into multiple lines!
- Start a separate line after a comma
- Experts recommend each line has 80 characters or less

In [ ]:
data["num_siblings"] = list(map(fn_sum,
                                data["num_underage_siblings"],
                                data["num_adult_siblings"])) # purpose = readability

<font size = "5">

Try it yourself!

- Write a function checking whether num_siblings $\ge$ 1
- Add a variable to the dataset called "has_siblings"
- Assign True/False to this variable using "apply()"

In [ ]:
# Write your own code

# look at additional external scripts
#

,age,num_underage_siblings,num_adult_siblings,can_vote,in_twenties,age_bracket,can_vote_map,num_siblings,has_siblings
0,18,0,1,True,False,Adult,True,1,True
1,29,0,0,True,True,Adult,True,0,False
2,15,1,0,False,False,Adolescent,False,1,True
3,32,1,1,True,False,Adult,True,2,True
4,6,0,0,False,False,Child,False,0,False

<font size = "5">

Try it yourself!

- Read the car dataset "data_raw/features.csv"
- Create a function that tests whether mpg $\ge$ 29
- Add a variable "mpg_above_29" which is True/False if mpg $\ge$ 29
- Store the new dataset to "data_clean/features.csv"

In [ ]:
# Write your own code

<font size = "5">

Try it yourself!

- Map can also be applied to simple lists!
- Create a lambda function with arguments {fruit,color}.
- The function returns the string <br>
" A {fruit} is {color}"
- Create the following two lists:

``` list_fruits  = ["banana","strawberry","kiwi"] ```

``` list_colors  = ["yellow","red","green"] ```
- Use the list(map()) function to output a list with the form

In [ ]:
# Write your own code

## <span style="color:darkblue"> IV. (Optional) External Scripts </span>

<font size = "5">

".ipynb" files ...

- Markdown + python code
- Great for interactive output!

".py" files ...

- Python (only) script
- Used for specific tasks
- Why? Split code into smaller, more manageable files


<font size = "5">

<table><tr>
<td style = "border:0px"> <img src="figures/screenshot_py_functions.png" alt="drawing" width="300"/>  </td>
<td style = "border:0px">

File with functions

 </td>
</tr></table>

**A module is just a Python program that ends with <br>
.py extension and a folder that contains a <br>
 module becomes a package!**

<font size = "5">

We can import functions into the working <br>
environment from a file

In [ ]:

import scripts.example_functions as ef

<font size = "5">

We reference them using the alias

In [ ]:
x = 1
print(ef.fn_quadratic(1))
print(ef.fn_quadratic(5))

ef.message_hello("Juan")

1
25

'hi Juan'


<font size = "5">

<table><tr>
<td style = "border:0px"> <img src="figures/screenshot_py_variables.png" alt="drawing" width="300"/>  </td>
<td style = "border:0px">

File with variables

- Storing values/settings
- Variables are global <br>
(can be referenced later)

</td>
</tr></table>

<font size = "5">

We can also import and reference variables

In [1]:
import scripts.example_variables as ev

In [ ]:
# When we run this program
# # the value of alpha will be overwritten

alpha = 1
print(alpha)
print(ev.alpha)

1
5

<font size = "5">

We can also use ``` from ``` and ``` * ``` <br>
to import variables directly into the working <br>
environment

In [ ]:
from scripts.example_variables import *

print(alpha)
print(beta)
print(gamma)
print(delta)

5
10
20
100